-- Fase 17-A — Treinos · Seed da base de exercícios (GERADO — não editar à mão)
--
--   Origem : data/training/exercise-base/exercises.json (versão 1.0.0)
--   Gerador: scripts/training/generate-exercise-base-migration.mjs
--   Conteúdo AUTORAL. Procedência e licença: data/training/exercise-base/ATTRIBUTION.md
--   Nenhuma imagem, vídeo, texto de instrução ou dado de terceiro entra aqui.
--
--   106 exercícios · 132 vínculos de músculo secundário
--
-- IDEMPOTENTE: o conflito é resolvido pelo índice único parcial em `system_code` das linhas
-- globais, então reaplicar ATUALIZA em vez de duplicar. As linhas entram com user_id nulo,
-- is_system_exercise = true e source = 'sistema' — base do sistema, somente leitura.

-- ─────────────────────────────────── Exercícios ───────────────────────────────────
with base(code, name, alt, primary_slug, equipment_slug, movement, etype, tracking, laterality) as (
  values
    ('supino_reto_barra', 'Supino reto com barra', 'Supino horizontal com barra', 'peitoral', 'barra', 'empurrar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('supino_reto_halteres', 'Supino reto com halteres', null, 'peitoral', 'halteres', 'empurrar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('supino_inclinado_barra', 'Supino inclinado com barra', null, 'peitoral', 'barra', 'empurrar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('supino_inclinado_halteres', 'Supino inclinado com halteres', null, 'peitoral', 'halteres', 'empurrar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('supino_declinado', 'Supino declinado', null, 'peitoral', 'barra', 'empurrar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('supino_maquina', 'Supino máquina', null, 'peitoral', 'maquina', 'empurrar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('crucifixo_reto_halteres', 'Crucifixo reto com halteres', null, 'peitoral', 'halteres', 'aducao', 'forca', 'peso_reps', 'bilateral'),
    ('crucifixo_inclinado', 'Crucifixo inclinado', null, 'peitoral', 'halteres', 'aducao', 'forca', 'peso_reps', 'bilateral'),
    ('voador_peitoral', 'Voador peitoral', 'Peck deck', 'peitoral', 'maquina', 'aducao', 'forca', 'peso_reps', 'bilateral'),
    ('crossover_polia', 'Crossover na polia', null, 'peitoral', 'cabo', 'aducao', 'forca', 'peso_reps', 'bilateral'),
    ('flexao_bracos', 'Flexão de braços', null, 'peitoral', 'peso_corporal', 'empurrar_horizontal', 'forca', 'peso_corporal_reps', 'bilateral'),
    ('paralelas_peitoral', 'Paralelas com foco no peitoral', null, 'peitoral', 'peso_corporal', 'empurrar_vertical', 'forca', 'peso_corporal_adicional', 'bilateral'),
    ('puxada_frontal', 'Puxada frontal', 'Pulldown pronado', 'dorsais', 'cabo', 'puxar_vertical', 'forca', 'peso_reps', 'bilateral'),
    ('puxada_neutra', 'Puxada neutra', null, 'dorsais', 'cabo', 'puxar_vertical', 'forca', 'peso_reps', 'bilateral'),
    ('puxada_supinada', 'Puxada supinada', null, 'dorsais', 'cabo', 'puxar_vertical', 'forca', 'peso_reps', 'bilateral'),
    ('barra_fixa_pronada', 'Barra fixa pronada', null, 'dorsais', 'peso_corporal', 'puxar_vertical', 'forca', 'peso_corporal_adicional', 'bilateral'),
    ('barra_fixa_supinada', 'Barra fixa supinada', null, 'dorsais', 'peso_corporal', 'puxar_vertical', 'forca', 'peso_corporal_adicional', 'bilateral'),
    ('remada_baixa', 'Remada baixa', null, 'costas', 'cabo', 'puxar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('remada_curvada_barra', 'Remada curvada com barra', null, 'costas', 'barra', 'puxar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('remada_unilateral_halter', 'Remada unilateral com halter', 'Serrote', 'costas', 'halteres', 'puxar_horizontal', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('remada_cavalinho', 'Remada cavalinho', null, 'costas', 'barra', 'puxar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('remada_maquina', 'Remada máquina', null, 'costas', 'maquina', 'puxar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('pulldown_bracos_estendidos', 'Pulldown com braços estendidos', null, 'dorsais', 'cabo', 'puxar_vertical', 'forca', 'peso_reps', 'bilateral'),
    ('pullover_polia', 'Pullover na polia', null, 'dorsais', 'cabo', 'puxar_vertical', 'forca', 'peso_reps', 'bilateral'),
    ('levantamento_terra', 'Levantamento terra', null, 'costas', 'barra', 'dobradica_quadril', 'forca', 'peso_reps', 'bilateral'),
    ('desenvolvimento_barra', 'Desenvolvimento com barra', null, 'ombros', 'barra', 'empurrar_vertical', 'forca', 'peso_reps', 'bilateral'),
    ('desenvolvimento_halteres', 'Desenvolvimento com halteres', null, 'ombros', 'halteres', 'empurrar_vertical', 'forca', 'peso_reps', 'bilateral'),
    ('desenvolvimento_maquina', 'Desenvolvimento na máquina', null, 'ombros', 'maquina', 'empurrar_vertical', 'forca', 'peso_reps', 'bilateral'),
    ('desenvolvimento_arnold', 'Desenvolvimento Arnold', null, 'ombros', 'halteres', 'empurrar_vertical', 'forca', 'peso_reps', 'bilateral'),
    ('elevacao_lateral_halteres', 'Elevação lateral com halteres', null, 'deltoide_lateral', 'halteres', 'abducao', 'forca', 'peso_reps', 'bilateral'),
    ('elevacao_lateral_polia', 'Elevação lateral na polia', null, 'deltoide_lateral', 'cabo', 'abducao', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('elevacao_frontal', 'Elevação frontal', null, 'deltoide_anterior', 'halteres', 'elevacao', 'forca', 'peso_reps', 'bilateral'),
    ('crucifixo_inverso', 'Crucifixo inverso', null, 'deltoide_posterior', 'halteres', 'puxar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('voador_inverso', 'Voador inverso', null, 'deltoide_posterior', 'maquina', 'puxar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('face_pull', 'Face pull', null, 'deltoide_posterior', 'cabo', 'puxar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('remada_alta', 'Remada alta', null, 'ombros', 'barra', 'elevacao', 'forca', 'peso_reps', 'bilateral'),
    ('encolhimento_barra', 'Encolhimento com barra', null, 'trapezio', 'barra', 'elevacao', 'forca', 'peso_reps', 'bilateral'),
    ('encolhimento_halteres', 'Encolhimento com halteres', null, 'trapezio', 'halteres', 'elevacao', 'forca', 'peso_reps', 'bilateral'),
    ('rosca_direta_barra', 'Rosca direta com barra', null, 'biceps', 'barra', 'flexao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('rosca_direta_polia', 'Rosca direta na polia', null, 'biceps', 'cabo', 'flexao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('rosca_alternada_halteres', 'Rosca alternada com halteres', null, 'biceps', 'halteres', 'flexao_cotovelo', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('rosca_simultanea', 'Rosca simultânea', null, 'biceps', 'halteres', 'flexao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('rosca_martelo', 'Rosca martelo', null, 'biceps', 'halteres', 'flexao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('rosca_scott', 'Rosca Scott', null, 'biceps', 'barra', 'flexao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('rosca_concentrada', 'Rosca concentrada', null, 'biceps', 'halteres', 'flexao_cotovelo', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('rosca_inclinada', 'Rosca inclinada', null, 'biceps', 'halteres', 'flexao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('rosca_inversa', 'Rosca inversa', null, 'antebracos', 'barra', 'flexao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('rosca_bayesian', 'Rosca Bayesian', null, 'biceps', 'cabo', 'flexao_cotovelo', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('triceps_polia_barra', 'Tríceps na polia com barra', null, 'triceps', 'cabo', 'extensao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('triceps_polia_corda', 'Tríceps na polia com corda', null, 'triceps', 'cabo', 'extensao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('triceps_frances', 'Tríceps francês', null, 'triceps', 'halteres', 'extensao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('triceps_testa', 'Tríceps testa', null, 'triceps', 'barra', 'extensao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('triceps_coice', 'Tríceps coice', null, 'triceps', 'halteres', 'extensao_cotovelo', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('triceps_maquina', 'Tríceps máquina', null, 'triceps', 'maquina', 'extensao_cotovelo', 'forca', 'peso_reps', 'bilateral'),
    ('supino_fechado', 'Supino fechado', null, 'triceps', 'barra', 'empurrar_horizontal', 'forca', 'peso_reps', 'bilateral'),
    ('paralelas', 'Paralelas', null, 'triceps', 'peso_corporal', 'empurrar_vertical', 'forca', 'peso_corporal_adicional', 'bilateral'),
    ('extensao_unilateral_polia', 'Extensão unilateral na polia', null, 'triceps', 'cabo', 'extensao_cotovelo', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('agachamento_livre', 'Agachamento livre', null, 'quadriceps', 'barra', 'agachamento', 'forca', 'peso_reps', 'bilateral'),
    ('agachamento_frontal', 'Agachamento frontal', null, 'quadriceps', 'barra', 'agachamento', 'forca', 'peso_reps', 'bilateral'),
    ('agachamento_smith', 'Agachamento no Smith', null, 'quadriceps', 'smith', 'agachamento', 'forca', 'peso_reps', 'bilateral'),
    ('agachamento_hack', 'Agachamento hack', null, 'quadriceps', 'maquina', 'agachamento', 'forca', 'peso_reps', 'bilateral'),
    ('leg_press_45', 'Leg press 45 graus', null, 'quadriceps', 'maquina', 'agachamento', 'forca', 'peso_reps', 'bilateral'),
    ('leg_press_horizontal', 'Leg press horizontal', null, 'quadriceps', 'maquina', 'agachamento', 'forca', 'peso_reps', 'bilateral'),
    ('cadeira_extensora', 'Cadeira extensora', null, 'quadriceps', 'maquina', 'extensao_joelho', 'forca', 'peso_reps', 'bilateral'),
    ('afundo', 'Afundo', null, 'quadriceps', 'halteres', 'agachamento', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('passada', 'Passada', 'Avanço caminhando', 'quadriceps', 'halteres', 'locomocao', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('agachamento_bulgaro', 'Agachamento búlgaro', null, 'quadriceps', 'halteres', 'agachamento', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('step_up', 'Step-up', null, 'quadriceps', 'halteres', 'locomocao', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('agachamento_sumo', 'Agachamento sumô', null, 'quadriceps', 'barra', 'agachamento', 'forca', 'peso_reps', 'bilateral'),
    ('hip_thrust', 'Hip thrust', null, 'gluteos', 'barra', 'dobradica_quadril', 'forca', 'peso_reps', 'bilateral'),
    ('elevacao_pelvica', 'Elevação pélvica', null, 'gluteos', 'peso_corporal', 'dobradica_quadril', 'forca', 'peso_corporal_adicional', 'bilateral'),
    ('coice_polia', 'Coice na polia', null, 'gluteos', 'cabo', 'dobradica_quadril', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('cadeira_abdutora', 'Cadeira abdutora', null, 'abdutores', 'maquina', 'abducao', 'forca', 'peso_reps', 'bilateral'),
    ('cadeira_adutora', 'Cadeira adutora', null, 'adutores', 'maquina', 'aducao', 'forca', 'peso_reps', 'bilateral'),
    ('stiff_barra', 'Stiff com barra', null, 'posteriores_coxa', 'barra', 'dobradica_quadril', 'forca', 'peso_reps', 'bilateral'),
    ('stiff_halteres', 'Stiff com halteres', null, 'posteriores_coxa', 'halteres', 'dobradica_quadril', 'forca', 'peso_reps', 'bilateral'),
    ('levantamento_terra_romeno', 'Levantamento terra romeno', 'RDL', 'posteriores_coxa', 'barra', 'dobradica_quadril', 'forca', 'peso_reps', 'bilateral'),
    ('mesa_flexora', 'Mesa flexora', null, 'posteriores_coxa', 'maquina', 'flexao_joelho', 'forca', 'peso_reps', 'bilateral'),
    ('cadeira_flexora', 'Cadeira flexora', null, 'posteriores_coxa', 'maquina', 'flexao_joelho', 'forca', 'peso_reps', 'bilateral'),
    ('flexora_em_pe', 'Flexora em pé', null, 'posteriores_coxa', 'maquina', 'flexao_joelho', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('good_morning', 'Good morning', null, 'posteriores_coxa', 'barra', 'dobradica_quadril', 'forca', 'peso_reps', 'bilateral'),
    ('nordic_curl', 'Nordic curl', null, 'posteriores_coxa', 'peso_corporal', 'flexao_joelho', 'forca', 'peso_corporal_reps', 'bilateral'),
    ('panturrilha_em_pe', 'Panturrilha em pé', null, 'panturrilhas', 'maquina', 'elevacao', 'forca', 'peso_reps', 'bilateral'),
    ('panturrilha_sentada', 'Panturrilha sentada', null, 'panturrilhas', 'maquina', 'elevacao', 'forca', 'peso_reps', 'bilateral'),
    ('panturrilha_leg_press', 'Panturrilha no leg press', null, 'panturrilhas', 'maquina', 'elevacao', 'forca', 'peso_reps', 'bilateral'),
    ('panturrilha_unilateral', 'Panturrilha unilateral', null, 'panturrilhas', 'halteres', 'elevacao', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('panturrilha_smith', 'Panturrilha no Smith', null, 'panturrilhas', 'smith', 'elevacao', 'forca', 'peso_reps', 'bilateral'),
    ('abdominal_tradicional', 'Abdominal tradicional', null, 'abdomen', 'peso_corporal', 'outros', 'forca', 'reps_sem_carga', 'bilateral'),
    ('abdominal_maquina', 'Abdominal máquina', null, 'abdomen', 'maquina', 'outros', 'forca', 'peso_reps', 'bilateral'),
    ('abdominal_polia', 'Abdominal na polia', null, 'abdomen', 'cabo', 'outros', 'forca', 'peso_reps', 'bilateral'),
    ('prancha', 'Prancha', null, 'abdomen', 'peso_corporal', 'estabilizacao', 'isometrico', 'duracao', 'bilateral'),
    ('prancha_lateral', 'Prancha lateral', null, 'abdomen', 'peso_corporal', 'estabilizacao', 'isometrico', 'duracao', 'unilateral_alternado'),
    ('elevacao_pernas', 'Elevação de pernas', null, 'abdomen', 'peso_corporal', 'outros', 'forca', 'reps_sem_carga', 'bilateral'),
    ('elevacao_joelhos', 'Elevação de joelhos', null, 'abdomen', 'peso_corporal', 'outros', 'forca', 'reps_sem_carga', 'bilateral'),
    ('abdominal_infra', 'Abdominal infra', null, 'abdomen', 'peso_corporal', 'outros', 'forca', 'reps_sem_carga', 'bilateral'),
    ('russian_twist', 'Russian twist', null, 'abdomen', 'anilhas', 'rotacao', 'forca', 'peso_reps', 'bilateral'),
    ('dead_bug', 'Dead bug', null, 'abdomen', 'peso_corporal', 'anti_rotacao', 'forca', 'reps_sem_carga', 'bilateral'),
    ('pallof_press', 'Pallof press', null, 'abdomen', 'cabo', 'anti_rotacao', 'forca', 'peso_reps', 'unilateral_alternado'),
    ('roda_abdominal', 'Roda abdominal', null, 'abdomen', 'outro', 'anti_rotacao', 'forca', 'reps_sem_carga', 'bilateral'),
    ('caminhada_esteira', 'Caminhada na esteira', null, 'cardiorrespiratorio', 'esteira', 'locomocao', 'cardio', 'distancia_duracao', 'bilateral'),
    ('corrida_esteira', 'Corrida na esteira', null, 'cardiorrespiratorio', 'esteira', 'locomocao', 'cardio', 'distancia_duracao', 'bilateral'),
    ('bicicleta_ergometrica', 'Bicicleta ergométrica', null, 'cardiorrespiratorio', 'bicicleta', 'locomocao', 'cardio', 'distancia_duracao', 'bilateral'),
    ('eliptico', 'Elíptico', null, 'cardiorrespiratorio', 'eliptico', 'locomocao', 'cardio', 'distancia_duracao', 'bilateral'),
    ('remo_ergometro', 'Remo ergométrico', null, 'cardiorrespiratorio', 'remo_ergometro', 'puxar_horizontal', 'cardio', 'distancia_duracao', 'bilateral'),
    ('escada', 'Escada', null, 'cardiorrespiratorio', 'escada', 'locomocao', 'cardio', 'duracao', 'bilateral'),
    ('corda', 'Corda', 'Pular corda', 'cardiorrespiratorio', 'corda', 'locomocao', 'cardio', 'duracao', 'bilateral')
)
insert into public.training_exercises (
  user_id, name, alternative_name,
  primary_muscle_group_id, equipment_id,
  movement_pattern, exercise_type, tracking_type, laterality,
  is_system_exercise, is_verified, system_code, source
)
select
  null, b.name, b.alt,
  mg.id, eq.id,
  b.movement, b.etype, b.tracking, b.laterality,
  true, true, b.code, 'sistema'
from base b
join public.training_muscle_groups mg
  on mg.user_id is null and mg.slug = b.primary_slug
left join public.training_equipment eq
  on eq.user_id is null and eq.slug = b.equipment_slug
on conflict (system_code) where user_id is null and system_code is not null do update
  set name                    = excluded.name,
      alternative_name        = excluded.alternative_name,
      primary_muscle_group_id = excluded.primary_muscle_group_id,
      equipment_id            = excluded.equipment_id,
      movement_pattern        = excluded.movement_pattern,
      exercise_type           = excluded.exercise_type,
      tracking_type           = excluded.tracking_type,
      laterality              = excluded.laterality;

-- ───────────────────────────── Músculos secundários ─────────────────────────────
-- Primeiro remove o que saiu da base (para a reexecução refletir edições no JSON)...
with links(code, group_slug) as (
  values
    ('supino_reto_barra', 'triceps'),
    ('supino_reto_barra', 'deltoide_anterior'),
    ('supino_reto_halteres', 'triceps'),
    ('supino_reto_halteres', 'deltoide_anterior'),
    ('supino_inclinado_barra', 'deltoide_anterior'),
    ('supino_inclinado_barra', 'triceps'),
    ('supino_inclinado_halteres', 'deltoide_anterior'),
    ('supino_inclinado_halteres', 'triceps'),
    ('supino_declinado', 'triceps'),
    ('supino_declinado', 'deltoide_anterior'),
    ('supino_maquina', 'triceps'),
    ('supino_maquina', 'deltoide_anterior'),
    ('crucifixo_reto_halteres', 'deltoide_anterior'),
    ('crucifixo_inclinado', 'deltoide_anterior'),
    ('voador_peitoral', 'deltoide_anterior'),
    ('crossover_polia', 'deltoide_anterior'),
    ('flexao_bracos', 'triceps'),
    ('flexao_bracos', 'deltoide_anterior'),
    ('flexao_bracos', 'abdomen'),
    ('paralelas_peitoral', 'triceps'),
    ('paralelas_peitoral', 'deltoide_anterior'),
    ('puxada_frontal', 'biceps'),
    ('puxada_frontal', 'trapezio'),
    ('puxada_frontal', 'antebracos'),
    ('puxada_neutra', 'biceps'),
    ('puxada_neutra', 'antebracos'),
    ('puxada_supinada', 'biceps'),
    ('barra_fixa_pronada', 'biceps'),
    ('barra_fixa_pronada', 'antebracos'),
    ('barra_fixa_supinada', 'biceps'),
    ('remada_baixa', 'biceps'),
    ('remada_baixa', 'trapezio'),
    ('remada_baixa', 'deltoide_posterior'),
    ('remada_curvada_barra', 'biceps'),
    ('remada_curvada_barra', 'trapezio'),
    ('remada_curvada_barra', 'lombar'),
    ('remada_unilateral_halter', 'biceps'),
    ('remada_unilateral_halter', 'trapezio'),
    ('remada_cavalinho', 'biceps'),
    ('remada_cavalinho', 'trapezio'),
    ('remada_maquina', 'biceps'),
    ('remada_maquina', 'trapezio'),
    ('pulldown_bracos_estendidos', 'triceps'),
    ('pulldown_bracos_estendidos', 'abdomen'),
    ('pullover_polia', 'triceps'),
    ('pullover_polia', 'peitoral'),
    ('levantamento_terra', 'gluteos'),
    ('levantamento_terra', 'posteriores_coxa'),
    ('levantamento_terra', 'lombar'),
    ('levantamento_terra', 'quadriceps'),
    ('levantamento_terra', 'trapezio'),
    ('levantamento_terra', 'antebracos'),
    ('desenvolvimento_barra', 'triceps'),
    ('desenvolvimento_barra', 'trapezio'),
    ('desenvolvimento_halteres', 'triceps'),
    ('desenvolvimento_halteres', 'trapezio'),
    ('desenvolvimento_maquina', 'triceps'),
    ('desenvolvimento_arnold', 'triceps'),
    ('desenvolvimento_arnold', 'trapezio'),
    ('elevacao_lateral_halteres', 'trapezio'),
    ('elevacao_lateral_polia', 'trapezio'),
    ('elevacao_frontal', 'peitoral'),
    ('crucifixo_inverso', 'trapezio'),
    ('crucifixo_inverso', 'costas'),
    ('voador_inverso', 'trapezio'),
    ('face_pull', 'trapezio'),
    ('remada_alta', 'trapezio'),
    ('remada_alta', 'biceps'),
    ('encolhimento_barra', 'antebracos'),
    ('encolhimento_halteres', 'antebracos'),
    ('rosca_direta_barra', 'antebracos'),
    ('rosca_direta_polia', 'antebracos'),
    ('rosca_alternada_halteres', 'antebracos'),
    ('rosca_simultanea', 'antebracos'),
    ('rosca_martelo', 'antebracos'),
    ('rosca_scott', 'antebracos'),
    ('rosca_concentrada', 'antebracos'),
    ('rosca_inclinada', 'antebracos'),
    ('rosca_inversa', 'biceps'),
    ('rosca_bayesian', 'antebracos'),
    ('supino_fechado', 'peitoral'),
    ('supino_fechado', 'deltoide_anterior'),
    ('paralelas', 'peitoral'),
    ('paralelas', 'deltoide_anterior'),
    ('agachamento_livre', 'gluteos'),
    ('agachamento_livre', 'posteriores_coxa'),
    ('agachamento_livre', 'lombar'),
    ('agachamento_livre', 'abdomen'),
    ('agachamento_frontal', 'gluteos'),
    ('agachamento_frontal', 'abdomen'),
    ('agachamento_frontal', 'lombar'),
    ('agachamento_smith', 'gluteos'),
    ('agachamento_hack', 'gluteos'),
    ('leg_press_45', 'gluteos'),
    ('leg_press_45', 'posteriores_coxa'),
    ('leg_press_horizontal', 'gluteos'),
    ('afundo', 'gluteos'),
    ('afundo', 'posteriores_coxa'),
    ('passada', 'gluteos'),
    ('passada', 'posteriores_coxa'),
    ('agachamento_bulgaro', 'gluteos'),
    ('agachamento_bulgaro', 'posteriores_coxa'),
    ('step_up', 'gluteos'),
    ('agachamento_sumo', 'gluteos'),
    ('agachamento_sumo', 'adutores'),
    ('hip_thrust', 'posteriores_coxa'),
    ('hip_thrust', 'quadriceps'),
    ('elevacao_pelvica', 'posteriores_coxa'),
    ('coice_polia', 'posteriores_coxa'),
    ('cadeira_abdutora', 'gluteos'),
    ('stiff_barra', 'gluteos'),
    ('stiff_barra', 'lombar'),
    ('stiff_halteres', 'gluteos'),
    ('stiff_halteres', 'lombar'),
    ('levantamento_terra_romeno', 'gluteos'),
    ('levantamento_terra_romeno', 'lombar'),
    ('levantamento_terra_romeno', 'trapezio'),
    ('mesa_flexora', 'panturrilhas'),
    ('good_morning', 'gluteos'),
    ('good_morning', 'lombar'),
    ('nordic_curl', 'gluteos'),
    ('prancha', 'lombar'),
    ('prancha', 'gluteos'),
    ('prancha_lateral', 'gluteos'),
    ('roda_abdominal', 'lombar'),
    ('roda_abdominal', 'dorsais'),
    ('bicicleta_ergometrica', 'quadriceps'),
    ('remo_ergometro', 'costas'),
    ('remo_ergometro', 'quadriceps'),
    ('escada', 'gluteos'),
    ('escada', 'quadriceps'),
    ('corda', 'panturrilhas')
)
delete from public.training_exercise_muscles m
using public.training_exercises e
where m.exercise_id = e.id
  and m.user_id is null
  and e.user_id is null
  and e.system_code is not null
  and not exists (
    select 1
      from links l
      join public.training_muscle_groups mg
        on mg.user_id is null and mg.slug = l.group_slug
     where l.code = e.system_code
       and mg.id = m.muscle_group_id
  );

-- ...e então insere/atualiza os vínculos atuais.
with links(code, group_slug, position) as (
  values
    ('supino_reto_barra', 'triceps', 0),
    ('supino_reto_barra', 'deltoide_anterior', 1),
    ('supino_reto_halteres', 'triceps', 0),
    ('supino_reto_halteres', 'deltoide_anterior', 1),
    ('supino_inclinado_barra', 'deltoide_anterior', 0),
    ('supino_inclinado_barra', 'triceps', 1),
    ('supino_inclinado_halteres', 'deltoide_anterior', 0),
    ('supino_inclinado_halteres', 'triceps', 1),
    ('supino_declinado', 'triceps', 0),
    ('supino_declinado', 'deltoide_anterior', 1),
    ('supino_maquina', 'triceps', 0),
    ('supino_maquina', 'deltoide_anterior', 1),
    ('crucifixo_reto_halteres', 'deltoide_anterior', 0),
    ('crucifixo_inclinado', 'deltoide_anterior', 0),
    ('voador_peitoral', 'deltoide_anterior', 0),
    ('crossover_polia', 'deltoide_anterior', 0),
    ('flexao_bracos', 'triceps', 0),
    ('flexao_bracos', 'deltoide_anterior', 1),
    ('flexao_bracos', 'abdomen', 2),
    ('paralelas_peitoral', 'triceps', 0),
    ('paralelas_peitoral', 'deltoide_anterior', 1),
    ('puxada_frontal', 'biceps', 0),
    ('puxada_frontal', 'trapezio', 1),
    ('puxada_frontal', 'antebracos', 2),
    ('puxada_neutra', 'biceps', 0),
    ('puxada_neutra', 'antebracos', 1),
    ('puxada_supinada', 'biceps', 0),
    ('barra_fixa_pronada', 'biceps', 0),
    ('barra_fixa_pronada', 'antebracos', 1),
    ('barra_fixa_supinada', 'biceps', 0),
    ('remada_baixa', 'biceps', 0),
    ('remada_baixa', 'trapezio', 1),
    ('remada_baixa', 'deltoide_posterior', 2),
    ('remada_curvada_barra', 'biceps', 0),
    ('remada_curvada_barra', 'trapezio', 1),
    ('remada_curvada_barra', 'lombar', 2),
    ('remada_unilateral_halter', 'biceps', 0),
    ('remada_unilateral_halter', 'trapezio', 1),
    ('remada_cavalinho', 'biceps', 0),
    ('remada_cavalinho', 'trapezio', 1),
    ('remada_maquina', 'biceps', 0),
    ('remada_maquina', 'trapezio', 1),
    ('pulldown_bracos_estendidos', 'triceps', 0),
    ('pulldown_bracos_estendidos', 'abdomen', 1),
    ('pullover_polia', 'triceps', 0),
    ('pullover_polia', 'peitoral', 1),
    ('levantamento_terra', 'gluteos', 0),
    ('levantamento_terra', 'posteriores_coxa', 1),
    ('levantamento_terra', 'lombar', 2),
    ('levantamento_terra', 'quadriceps', 3),
    ('levantamento_terra', 'trapezio', 4),
    ('levantamento_terra', 'antebracos', 5),
    ('desenvolvimento_barra', 'triceps', 0),
    ('desenvolvimento_barra', 'trapezio', 1),
    ('desenvolvimento_halteres', 'triceps', 0),
    ('desenvolvimento_halteres', 'trapezio', 1),
    ('desenvolvimento_maquina', 'triceps', 0),
    ('desenvolvimento_arnold', 'triceps', 0),
    ('desenvolvimento_arnold', 'trapezio', 1),
    ('elevacao_lateral_halteres', 'trapezio', 0),
    ('elevacao_lateral_polia', 'trapezio', 0),
    ('elevacao_frontal', 'peitoral', 0),
    ('crucifixo_inverso', 'trapezio', 0),
    ('crucifixo_inverso', 'costas', 1),
    ('voador_inverso', 'trapezio', 0),
    ('face_pull', 'trapezio', 0),
    ('remada_alta', 'trapezio', 0),
    ('remada_alta', 'biceps', 1),
    ('encolhimento_barra', 'antebracos', 0),
    ('encolhimento_halteres', 'antebracos', 0),
    ('rosca_direta_barra', 'antebracos', 0),
    ('rosca_direta_polia', 'antebracos', 0),
    ('rosca_alternada_halteres', 'antebracos', 0),
    ('rosca_simultanea', 'antebracos', 0),
    ('rosca_martelo', 'antebracos', 0),
    ('rosca_scott', 'antebracos', 0),
    ('rosca_concentrada', 'antebracos', 0),
    ('rosca_inclinada', 'antebracos', 0),
    ('rosca_inversa', 'biceps', 0),
    ('rosca_bayesian', 'antebracos', 0),
    ('supino_fechado', 'peitoral', 0),
    ('supino_fechado', 'deltoide_anterior', 1),
    ('paralelas', 'peitoral', 0),
    ('paralelas', 'deltoide_anterior', 1),
    ('agachamento_livre', 'gluteos', 0),
    ('agachamento_livre', 'posteriores_coxa', 1),
    ('agachamento_livre', 'lombar', 2),
    ('agachamento_livre', 'abdomen', 3),
    ('agachamento_frontal', 'gluteos', 0),
    ('agachamento_frontal', 'abdomen', 1),
    ('agachamento_frontal', 'lombar', 2),
    ('agachamento_smith', 'gluteos', 0),
    ('agachamento_hack', 'gluteos', 0),
    ('leg_press_45', 'gluteos', 0),
    ('leg_press_45', 'posteriores_coxa', 1),
    ('leg_press_horizontal', 'gluteos', 0),
    ('afundo', 'gluteos', 0),
    ('afundo', 'posteriores_coxa', 1),
    ('passada', 'gluteos', 0),
    ('passada', 'posteriores_coxa', 1),
    ('agachamento_bulgaro', 'gluteos', 0),
    ('agachamento_bulgaro', 'posteriores_coxa', 1),
    ('step_up', 'gluteos', 0),
    ('agachamento_sumo', 'gluteos', 0),
    ('agachamento_sumo', 'adutores', 1),
    ('hip_thrust', 'posteriores_coxa', 0),
    ('hip_thrust', 'quadriceps', 1),
    ('elevacao_pelvica', 'posteriores_coxa', 0),
    ('coice_polia', 'posteriores_coxa', 0),
    ('cadeira_abdutora', 'gluteos', 0),
    ('stiff_barra', 'gluteos', 0),
    ('stiff_barra', 'lombar', 1),
    ('stiff_halteres', 'gluteos', 0),
    ('stiff_halteres', 'lombar', 1),
    ('levantamento_terra_romeno', 'gluteos', 0),
    ('levantamento_terra_romeno', 'lombar', 1),
    ('levantamento_terra_romeno', 'trapezio', 2),
    ('mesa_flexora', 'panturrilhas', 0),
    ('good_morning', 'gluteos', 0),
    ('good_morning', 'lombar', 1),
    ('nordic_curl', 'gluteos', 0),
    ('prancha', 'lombar', 0),
    ('prancha', 'gluteos', 1),
    ('prancha_lateral', 'gluteos', 0),
    ('roda_abdominal', 'lombar', 0),
    ('roda_abdominal', 'dorsais', 1),
    ('bicicleta_ergometrica', 'quadriceps', 0),
    ('remo_ergometro', 'costas', 0),
    ('remo_ergometro', 'quadriceps', 1),
    ('escada', 'gluteos', 0),
    ('escada', 'quadriceps', 1),
    ('corda', 'panturrilhas', 0)
)
insert into public.training_exercise_muscles (user_id, exercise_id, muscle_group_id, role, position)
select null, e.id, mg.id, 'secundario', l.position
from links l
join public.training_exercises e
  on e.user_id is null and e.system_code = l.code
join public.training_muscle_groups mg
  on mg.user_id is null and mg.slug = l.group_slug
on conflict (exercise_id, muscle_group_id) do update
  set role     = excluded.role,
      position = excluded.position;
